{% set version = "2.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-transformer
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/SantanderMetGroup/transformeR/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ccac13724e170914020fd2872714cb882a918f1c03754409875201d38112157d

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcppeigen
    - r-abind
    - r-akima
    - r-fields
    - r-kohonen
    - r-magrittr
    - r-sp
  run:
    - r-base
    - r-rcppeigen
    - r-abind
    - r-akima
    - r-fields
    - r-kohonen
    - r-magrittr
    - r-sp

test:
  commands:
    - $R -e "library('transformeR')"           # [not win]
    - "\"%R%\" -e \"library('transformeR')\""  # [win]

about:
  home: https://github.com/SantanderMetGroup/climate4R
  summary: Tools for climate data analysis, visualization and manipulation. A building block of the climate4R Framework <https://github.com/SantanderMetGroup/climate4R>.
  doc_url: https://github.com/SantanderMetGroup/transformeR/wiki
  dev_url: https://github.com/SantanderMetGroup/transformeR
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa
    - miturbide
    - mariadlor


# Package: transformeR
# Depends: R(>= 3.5.0)
# Imports: abind, akima, fields, graphics, grDevices, magrittr, parallel, RcppEigen, sp, stats, utils, kohonen
# Suggests: downscaleR, climate4R.datasets, climate4R.indices, loadeR, loadeR.ECOMS, visualizeR
# Type: Package
# Title: A climate4R package for general climate data manipulation and transformation
# Version: 2.1.0
# Date: 2021-03-17
# Authors@R: c(person("Bedia", "Joaquin", email = "bediaj@unican.es", role = c("aut","cre"), comment = c(ORCID = "0000-0001-6219-4312")), person("Jorge", "Bano Medina", email = "bmedina@ifca.unican.es", role = "aut"), person("Ana", "Casanueva", email = "ana.casanueva@unican.es", role = "aut"), person("Matteo", "De Felice", email = "matteo.defelice@enea.it", role = "ctb"), person("Jose Manuel", "Gutierrez", email = "gutierjm@unican.es", role = "aut"), person("Sixto", "Herrera", email = "herreras@unican.es", role = "aut"), person("Maialen", "Iturbide", email = "miturbide@ifca.unican.es", role = "aut", comment = c(ORCID = "0000-0002-5048-0941")), person("Juan A.", "Fernandez", email = "juan.fernandez@unican.es", role = "aut"))
# BugReports: https://github.com/SantanderMetGroup/transformeR/issues
# URL: http://www.meteo.unican.es/climate4r
# Encoding: UTF-8
# Description: Tools for climate data analysis, visualization and manipulation. A building block of the climate4R Framework <http://www.meteo.unican.es/climate4R>.
# License: file LICENSE
# LazyData: false
# RoxygenNote: 7.1.1
